[package]
name = "reflect_mac"
version = "0.0.1"
authors = ["Simon Ask Ulsnes <simon@ulsnes.dk>"]
license = "MIT"

[lib]
name = "reflect_mac"
path = "src/lib.rs"
plugin = true
test = false

[dependencies]
phf = "*"
phf_mac = "*"

[[test]]
name = "tests"
