[package]
name = "reflect_mac"
version = "0.0.1"
authors = ["Simon Ask Ulsnes <simon@ulsnes.dk>"]

[lib]
name = "reflect_mac"
path = "src/lib.rs"
plugin = true
test = false

[dependencies.reflect]
path = "../reflect"
version = "=0.0.1"

[[test]]
name = "tests"
