[package]
name = "reflect"
version = "0.0.1"
authors = ["Simon Ask Ulsnes <simon@ulsnes.dk>"]
license = "MIT"

[dependencies]
phf = "*"
phf_mac = "*"

[dependencies.reflect_mac]
path = "../reflect_mac"
version = "=0.0.1"

[[test]]
name = "tests"
